language: scala
before_install:
  - git fetch --tags
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.5

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
     
jobs:
  include:
    - name: test
      script: sbt +test
    - name: formatting
      script: sbt scalafmtCheck test:scalafmtCheck
    - stage: release
      script: sbt ci-release


